### ISSUE TITLE
index.js file would be appreciated when used with a bundler like web pack

### ISSUE THREAD

**Issue by ShukantPal** [mcollina/perf_hooks#1]

**Comment by mcollina** [comment]
why are you using this with webpack? This module should really not be used.
Il 29 feb 2020, 02:33 +0100, Sukant Pal <notifications@github.com>, ha scritto:

**Comment by ShukantPal** [comment]
@mcollina I have some code that needs to run on Node.js and should bundle with webpack to run in a browser environment. The only way to access `performance.now` on Node.js is with the perf_hooks module (right?). However, I need a dummy module for webpack.

**Comment by mcollina** [comment]
You should be not depending on this module. It’s just a placeholder for a node core module. Remove it from package.json and add some config to map it to nothing.
